services:
  frontend:
    image: ghcr.io/bezbee25/store-multitenants-frontend:latest
    container_name: store-multitenants-site
    restart: always
    ports:
      - "${PORT_FRONTEND:-3340}:80"
    environment:
      NODE_ENV: production
    networks:
      - woxxapp-network

  backend:
    image: ghcr.io/bezbee25/store-multitenants-backend:latest
    container_name: store-multitenants-api
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@woxxapp-db:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      WOXX_PAY_API_URL: ${WOXX_PAY_API_URL:-http://woxx-pay-api:8000}
      WOXX_PAY_M2M_CLIENT_ID: ${WOXX_PAY_M2M_CLIENT_ID}
      WOXX_PAY_M2M_CLIENT_SECRET: ${WOXX_PAY_M2M_CLIENT_SECRET}
      WOXX_PAY_PUBLIC_KEY: ${WOXX_PAY_PUBLIC_KEY}
    networks:
      - woxxapp-network
      - woxxpay_private_api

networks:
  woxxapp-network:
    external: true
    name: woxxapp-store_woxxapp-network
  woxxpay_private_api:
    external: true
